//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShuDu.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ShuDu.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Sample {
            get {
                object obj = ResourceManager.GetObject("Sample", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Blocks&quot;:[{&quot;Lines&quot;:[{&quot;Text&quot;:&quot;7&quot;,&quot;BoundingPolygon&quot;:[{&quot;X&quot;:17,&quot;Y&quot;:7},{&quot;X&quot;:34,&quot;Y&quot;:8},{&quot;X&quot;:34,&quot;Y&quot;:32},{&quot;X&quot;:17,&quot;Y&quot;:31}],&quot;Words&quot;:[{&quot;Text&quot;:&quot;7&quot;,&quot;BoundingPolygon&quot;:[{&quot;X&quot;:22,&quot;Y&quot;:7},{&quot;X&quot;:34,&quot;Y&quot;:8},{&quot;X&quot;:33,&quot;Y&quot;:32},{&quot;X&quot;:20,&quot;Y&quot;:31}],&quot;Confidence&quot;:0.994}]},{&quot;Text&quot;:&quot;6&quot;,&quot;BoundingPolygon&quot;:[{&quot;X&quot;:183,&quot;Y&quot;:8},{&quot;X&quot;:199,&quot;Y&quot;:8},{&quot;X&quot;:199,&quot;Y&quot;:31},{&quot;X&quot;:183,&quot;Y&quot;:31}],&quot;Words&quot;:[{&quot;Text&quot;:&quot;6&quot;,&quot;BoundingPolygon&quot;:[{&quot;X&quot;:183,&quot;Y&quot;:8},{&quot;X&quot;:193,&quot;Y&quot;:8},{&quot;X&quot;:193,&quot;Y&quot;:31},{&quot;X&quot;:183,&quot;Y&quot;:31}],&quot;Confidence&quot;:0.995}]},{&quot;Text&quot;:&quot;8&quot;,&quot;BoundingPolygon&....
        /// </summary>
        internal static string SampleJson {
            get {
                return ResourceManager.GetString("SampleJson", resourceCulture);
            }
        }
    }
}
